# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
enable_free_tier: false
reviews:
  high_level_summary: false
  review_status: false
  commit_status: false
  collapse_walkthrough: false
  changed_files_summary: false
  sequence_diagrams: false
  estimate_code_review_effort: false
  assess_linked_issues: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  suggested_reviewers: false
  in_progress_fortune: false
  poem: false
  enable_prompt_for_ai_agents: false
  abort_on_close: false
  auto_review:
    enabled: false
    auto_incremental_review: false
