name: Update MyHours Workflow

on:
  workflow_dispatch:

jobs:
  update-hours:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Set up git user
        run: |
          git config --global user.email "rmckenzi@rpmdp.com"
          git config --global user.name "Robert McKenzie"

      - name: Set up git remote with PAT
        env:
          MY_GH_PAT: ${{ secrets.MY_GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${MY_GH_PAT}@github.com/${GITHUB_REPOSITORY}.git

      - name: Create steam_vars.txt from secrets
        run: |
          echo "STEAM_API_KEY=${{ secrets.STEAM_API_KEY }}" > steam_vars.txt
          echo "STEAM_ID=${{ secrets.STEAM_USER_ID }}" >> steam_vars.txt

      - name: Run update-myhours-workflow-v2.py
        env:
          STEAM_GAME_ID: ${{ secrets.STEAM_GAME_ID }}
        run: |
          python ./M1XZG/scripts/update-myhours-workflow-v2.py $STEAM_GAME_ID

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md TMP-README.md
          git commit -m "Update Steam playtime hours"
          git push
