name: Update VRChat Hours

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # Runs daily at 6:00 UTC

jobs:
  update-vrchours:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi

      - name: Set execute permissions on scripts
        run: chmod +x scripts/update-vrchours.sh scripts/update-myhours.py

      - name: Run update-vrchours.sh
        env:
          STEAM_USER_ID: ${{ secrets.STEAM_USER_ID }}
          STEAM_GAME_ID: ${{ secrets.STEAM_GAME_ID }}
          PYTHONPATH: $GITHUB_WORKSPACE/scripts/python-requirements
        run: |
          ./scripts/update-vrchours.sh "$GITHUB_WORKSPACE" "$STEAM_USER_ID" "$STEAM_GAME_ID"