name: Update VRChat Hours

on:
  schedule:
    - cron: '0 2 * * *'  # Corrected cron to run every 2 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-hours:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Python virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install minsert

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh -y

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Fix script permissions and line endings
        run: |
          chmod +x ./scripts/update-vrchours-workflow.sh
          chmod +x ./scripts/update-myhours.py

      - name: Run update-vrchours script
        env:
          STEAM_USER_ID: ${{ secrets.STEAM_USER_ID }}
          STEAM_GAME_ID: ${{ secrets.STEAM_GAME_ID }}
        run: |
          source venv/bin/activate
          ./scripts/update-vrchours-workflow.sh . $STEAM_USER_ID $STEAM_GAME_ID