name: Update MyHours v2 (SteamAPI)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Runs every hour

concurrency:
  group: update-vrchat-hours-v2
  cancel-in-progress: true

jobs:
  update-hours:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Set up git user
        run: |
          git config --global user.email "rmckenzi@rpmdp.com"
          git config --global user.name "Robert McKenzie"

      - name: Set up git remote with PAT
        env:
          GH_TOKEN: ${{ secrets.MY_GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${MY_GH_PAT}@github.com/${GITHUB_REPOSITORY}.git

      - name: Create steam_vars.txt from secrets
        run: |
          echo "STEAM_API_KEY=${{ secrets.STEAM_API_KEY }}" > steam_vars.txt
          echo "STEAM_ID=${{ secrets.STEAM_USER_ID }}" >> steam_vars.txt

      - name: Run update-myhours-workflow-v2.sh
        env:
          STEAM_GAME_ID: ${{ secrets.STEAM_GAME_ID }}
          STEAM_USER_ID: ${{ secrets.STEAM_USER_ID }}
          GH_TOKEN: ${{ secrets.MY_GH_PAT }}
        run: |
          ./scripts/update-vrchours-workflow-v2.sh "$GITHUB_WORKSPACE" "$STEAM_GAME_ID"
